- name: install nginx
  hosts: frontend
  become: true
  vars_files:
    - variables.yaml
  tasks: 
    - name: install nginx server
      ansible.builtin.package:
        name: nginx
        state: present

    - name: enable the nginx
      service:
        name: nginx
        enabled: true

    - name: start nginx server
      service:
        name: nginx
        state: started

    - name: check the status of nginx
      service:
      systemctl:
        name: nginx
        state: status

