- name: passing the variables by using the prompt 
  hosts: all
  become: true

  vars_files:
    - variables.yaml

  vars_prompt:
    - name: username
      prompt: "enter the ansible username"
      private: no

    - name: passwd
      prompt: "enter the ansible passwd"
      private: yes

  tasks:
    - name: "printing the all passing credentials"
      debug:
        msg: "the ansible username is {{ username }} and password is {{ passwd}}"
        msg: "Successfully done"
      