- name: to pass the variables by using the CMD
  hosts: all
  become: true

  vars_files:
    - variables.yaml

  tasks:
    - name: to pass the variables in cmd
      debug:
        msg: "my name is {{ name }}"



        # ansible-playbook -i inventory.ini -e "name='lokesh'" 08-vars.yaml