- name: printing the ansible facts 
  hosts: frontend
  become: true

  vars_files:
    - variables.yaml

  tasks:
    - name: print the facts
      debug:
        msg: "{{ ansible_facts | output.txt }}"

        
- name: save ansible facts locally
  copy:
    content: "{{ ansible_facts }}"
    dest: /tmp/output.txt
