- name : gathering facts
  hosts: localhost
  become: true

  vars_files:
    - variables.yaml

  tasks:
    - name: gathering the facts from the server
      debug:
        msg: "{{ ansible_facts }}"