- name: check the distribution of the server
  hosts: localhost
  become: true

  vars_files:
    - variables.yaml

  vars:
    distribution: "{{ facts.json.distribution }}"

  tasks:
    - name: check the which distribution for this server 
      debug:
        msg: "the given distribution is {{distribution.name }}"
      when: facts.json.distribution == "Redhat"