- name: check the distribution of the server
  hosts: localhost
  become: true

  vars_files:
    - variables.yaml

  vars_prompt:
    name: NAME
    prompt: "enter the server distribution :" 
    private: no

  
  tasks:
    - name: check the which distribution for this server 
      debug:
        msg: "the given distribution is {{ NAME }}"
      when: NAME == {{ name }}