- name: check the distribution of the server
  hosts: localhost
  become: true

  vars_files:
    - variables.yaml

  vars:
    NAME: "Redhat"

  when: NAME == "Redhat"


  tasks:
    - name: check the which distribution for this server 
      debug:
        msg: "{{ ansible_distribution.NAME }}"