- name: check the distribution of the server
  hosts: localhost
  become: true

  vars_files:
    - variables.yaml

  vars:
    NAME: "{{ NAME}}"
  when: NAME == "Redhat"


  tasks:
    - name: ccheck the which distribution for this server 
      debug:
        msg: "{{ ansible_distribution }}"