- name: even or add
  hosts: localhost
  become: true

  vars_files:
    - variables.yaml

  vars_prompt:
    - name: number
      prompt: "enter the number to check even or odd :"
      private: no

  # vars: 
  #   number: 10
  
  tasks:
    - name: check the {{ number }} is even or odd
      debug:
        msg: "the given number {{ number }} is even"
        when: number % 2 == 0

    - name: check the {{ number }} is even or odd
      debug:
        msg: "the given number {{ number }} is odd"
        when: number % 2 != 0

  