- name: even or add
  hosts: localhost
  become: true

  vars_files:
    - variables.yaml


  vars_prompt:
    - name: number
      prompt: "enter the number for value"
      private: no

  # vars: 
  #   number: 10
  
  tasks:
    - name: even
      debug:
        msg: "the given number {{ number }} is even"
      when: number | int % 2 == 0

    - name: odd
      debug:
        msg: "the given number {{ number }} is odd"
      when: number | int % 2 != 0
  