- name: filter the topics using the topics
  hosts: localhost
  become: true

  vars_files:
    - variables.yaml
  
  vars:
    topics: apple, banana, orange, graps

    tagMap:
      apple: fruit
      banana: fruit
      orange: fruit
      graps: fruit

    full_name: lokesh kumar

    tagList: [
        {
            "key": "apple",
            "value": "fruit"
        },
        {
            "key": "banana",
            "value": "fruit"
        },
        {
            "key": "orange",
            "value": "fruit"
        },
        {
            "key": "graps",
            "value": "fruit"
        }
    ]

  tasks:
  - name: printing the topics
    debug:
      msg: "the topics are {{ topics.split(',') }}" 

  - name: print the default message
    debug:
      msg: "Hello, welcome Lokesh {{ message | default('Good Morning') }}"

  - name: convert map to list 
    debug: 
      msg: "{{ tagMap | dict2items }}"

  - name: convert list to map 
    debug:
      msg: "{{ tagList | items2dict }}"

  - name: convert to uppercase 
    debug:
      msg: "{{ topics.upper() }}"

  - name: convert to uppercase 
    debug:
      msg: "{{ full_name | upper }}"