- name: filter the topics using the topics
  hosts: localhost
  become: true

  vars_files:
    - variables.yaml

  vars:
    topics: apple, banana, orange, graps

  tasks:
  - name: printing the topics
    debug:
      msg: "the topics are {{ topics.split(',') }}" 

  - name: print the default message
    debug:
      msg: "The port is {{ app_port | default(8080) }}"