- namme: error handling
  hosts: localhost
  become: true

  vars_files:
    - variables.yaml
  
  tasks:
  - name: check the user output
    command: ls -ltr
    register: users_output

  - name: print
    debug:
      msg: "{{ users_output }}"

    #command: id roboshop