- name: error handling
  hosts: localhost
  become: yes
  connection: local

  vars_files:
    - variables.yaml
  
  tasks:
  - name: check the id 
    command: id roboshop
    register: user_output
    ignore_errors: true

  - name: create user 
    command: useradd roboshop
    when: user_output.rc ! = 0


