- name: provisioning the infrastructure
  hosts: local
  connections: true
  become: yes

  vars:
    instances: ["mongodb", "redis" ,"rabitmq" ,"mysqldb"]
    image_id: ami-0220d79f3f480ecf5

  tasks:
  - name: creating the instances
    amazon.aws.ec2_instance:
      name: "robo-{{ item }}"
      instance_type: t3.micro
      security_groups:
        - "robo-{{ item }}"
        - robo-common
      image_id: "{{ image_id }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the output
    debug:
      msg: "{{ ec2_output }}"
      
